sudo: required
os: linux
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6 C_COMPILER=clang-3.6

before_install:
- cd "${TRAVIS_BUILD_DIR}"

script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=$COMPILER ..
- make -j4
- ./AshleyCPPTest

branches:
  only:
    - master
